Enforce env user and provide a useful error message
smartcontractkit/chainlink-env pull request #380
Opened 2023-03-21 18:58 UTC by tateexon

We end up triaging a lot of errors to test runs in the cluster that do not have names associated which makes it difficult to know who to ask questions. This enforces the env user.

2023-03-21 19:15 UTC, kalverra requested changes

2023-03-21 19:15 UTC, kalverra commented on environment/environment.go
> +		panic(fmt.Sprintf("missing owner environment variable, please set %s to your name or if you are seeing this in CI please set it to ${{ github.actor }}", config.EnvVarUser))
Can we use `log.Fatal()` instead of a panic?

2023-03-22 00:02 UTC, AnieeG approved these changes

2023-03-22 03:40 UTC, kalverra approved these changes

2023-03-23 20:35 UTC, merged